# Generated by Django 3.2.9 on 2021-12-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='books'),
        ),
    ]
